name: mcb
description: "Minecraft Box"

publish_to: 'none'

version: 1.3.0+4

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.5.3
  dynamic_color: ^1.8.1
  package_info_plus: ^9.0.0
  json_rpc_2: ^4.0.0
  web_socket_channel: ^3.0.3
  crypto: ^3.0.6
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  dio: ^5.9.0
  device_info_plus: ^12.3.0
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/icon/icon.png
    - assets/img/logo/flutter.png
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansCJKsc-VF.ttf